name: Create GitHub Issue

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload Some Attachments
        id: upload_some_attachments
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: "**/reports/**"

      - name: Return file tail lines
        id: return-tail-lines
        run: |
          tail -n 10 ./reports/tests/test/classes/com.github.copilot.ui.test.CopilotChatTest.html > tail_output.txt
          echo "::set-output name=tail_lines::$(cat tail_output.txt)"

      - name: Track failure with GitHub Issue
        # Don't add condition for testing purpose now.
        # if: failure()
        id: create-github-issue
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const issueTitle = "UI test failed";
            const issueBody = `
              See reports from failed UI tests in the attachments. [link](${{ steps.upload_some_attachments.outputs.artifact-url }})
              Tailed logs: ${{steps.return-tail-lines.outputs.tail_lines}}
            `;
            const labels = ["automated issue"];
            const issue = await github.rest.issues.create({
              owner,
              repo,
              title: issueTitle,
              body: issueBody,
              labels
            });
            console.log(`Created issue https://github.com/${owner}/${repo}/issues/${issue.data.number}`);
            return issue.data.number
