name: Create GitHub Issue

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload Some Attachments
        id: upload_some_attachments
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: "**/reports/**"

      - name: Track failure with GitHub Issue
        id: create-github-issue
        uses: actions/github-script@v7
        with:
          script: |
            const createIssue = require('./.github/workflows/scripts/create-issue.js');
            await createIssue({context});
