name: Create GitHub Issue

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload Some Attachments
        id: upload_some_attachments
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: "**/reports/**"

      - name: Track failure with GitHub Issue
        # ./reports/tests-ui/build/reports/tests/test/classes/com.github.copilot.ui.test.CopilotChatTest.html
        # Don't add condition for testing purpose now.
        # if: failure()
        id: create-github-issue
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const readline = require('readline');
            const path = require('path');
            
            async function readLastLines(filePath, numLines) {
              const fileStream = fs.createReadStream(filePath);
              const rl = readline.createInterface({
                input: fileStream,
                crlfDelay: Infinity
              });
            
              const lines = [];
              for await (const line of rl) {
                lines.push(line);
                if (lines.length > numLines) {
                  lines.shift();
                }
              }
            
              return lines;
            }
            
            async function readAllFilesInDirectory(directory, numLines) {
              const files = fs.readdirSync(directory);
              let allLines = '';
              for (const file of files) {
                const filePath = path.join(directory, file);
                if (fs.statSync(filePath).isFile()) {
                  const lines = await readLastLines(filePath, numLines);
                  allLines += `\nFile: ${file}\n${lines.join('\n')}\n`;
                }
              }
              return allLines;
            }

            const { owner, repo } = context.repo;
            const issueTitle = "UI test failed";
            const issueBody = `
              See reports from failed UI tests in the attachments. [link](${{ steps.upload_some_attachments.outputs.artifact-url }})
              Logs: 
              \`\`\`
              ${await readAllFilesInDirectory('./reports/tests-ui/build/reports/tests/test/classes', 100)}
              \`\`\`
            `;
            const labels = ["automated issue"];
            const issue = await github.rest.issues.create({
              owner,
              repo,
              title: issueTitle,
              body: issueBody,
              labels
            });
            console.log(`Created issue https://github.com/${owner}/${repo}/issues/${issue.data.number}`);
            return issue.data.number
