name: Create GitHub Issue

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload Some Attachments
        id: upload_some_attachments
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-error-reports_${{ matrix.os }}_${{ matrix.ide_version }}
          path: "**/screenshots/*.png"

      - name: Track failure with GitHub Issue
        # Don't add condition for testing purpose now.
        # if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const issueTitle = "UI test failed";
            const issueBody = `
              See reports from failed UI tests in the attachments. 1: ${{ steps.upload_some_attachments.outputs }}, 2: ${{ steps.upload_some_attachments.artifact-id }},
              3: ${{ steps.upload_some_attachments.artifact-url }}, 4: ${{ steps.upload_some_attachments.outputs.artifact-url }}, 5: ${{ steps.upload_some_attachments.output.artifact-url }},
              6: ${{ steps.upload_some_attachments }}
            `;
            const labels = ["automated issue"];
            const issue = await github.rest.issues.create({
              owner,
              repo,
              title: issueTitle,
              body: issueBody,
              labels,
            });
            return issue.data.number;
