name: Create GitHub Issue

on:
  push:
    branches:
      - main

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create GitHub Issue
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const issueTitle = "New Issue Created by GitHub Action";
            const issueBody = "This issue was created automatically by the GitHub Action.";
            const labels = ["automated issue"];
            await github.rest.issues.create({
              owner,
              repo,
              title: issueTitle,
              body: issueBody,
              labels,
            });
